/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.redstone.persistence.avro.entity;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PackTitle {
  T_MarketDataSubscribe, T_MarketDataLevel1, T_Order, T_Next  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PackTitle\",\"namespace\":\"io.ffreedom.persistence.avro.entity\",\"symbols\":[\"T_MarketDataSubscribe\",\"T_MarketDataLevel1\",\"T_Order\",\"T_Next\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
